name: Setup tools
description: 'Setup tools for repo workflows'

inputs:
  install-nodejs:
    description: "Install nodejs and setup repo's npm package"
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup node.js and install dependencies
      if: inputs.install-nodejs == 'true'
      uses: ./.github/actions/nodejs-ci
      with:
        node-version: '18'
